version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      docusaurus:
        patterns:
        - "@docusaurus*"
        update-types:
        - "minor"
        - "patch"
      eslint:
        patterns:
        - "eslint"
        - "eslint-*"
        update-types:
        - "minor"
        - "patch"
      swc:
        patterns:
        - "@swc"
        - "swc-*"
        update-types:
        - "minor"
        - "patch"
      react:
        patterns:
        - "react"
        - "react-*"
        update-types:
        - "minor"
        - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
