{
 "title": "SV Aggregation Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_info,k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\", namespace=\"$namespace\"},exported_container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "svs/s" } },
   "targets": [
    {
     "expr": "sum by (op)(rate(farm_data_aggregation_single_views_total{k8sCluster=~\"$cluster\", namespace=~\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Current Aggregation Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(farm_data_aggregation_single_views_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SV by Operation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (op)(farm_data_aggregation_single_views_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Mean Compression Rate",
   "type": "gauge",
   "description": "Percentage of internal-update events that are \"compacted\", that is, only the last event is actually processed, since the execution of all the events would still lead to the same outcome",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (container)(rate(farm_data_msg_compression_rate_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval])) / avg by (container)(rate(farm_data_msg_compression_rate_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Process Time per Unit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(unit) (rate(farm_data_aggregation_unit_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) / sum by(unit) (rate(farm_data_aggregation_unit_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Mean Compression Rate",
   "type": "timeseries",
   "description": "Percentage of internal-update events that are \"compacted\", that is, only the last event is actually processed, since the execution of all the events would still lead to the same outcome",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(unit) (rate(farm_data_msg_compression_rate_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) / sum by(unit) (rate(farm_data_msg_compression_rate_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "Compression Rate"
    }
   ]
  },
  {
   "title": "Msg Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum (rate(farm_data_processed_msg_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Current Aggregation Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(farm_data_processed_msg_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Message Payload Size",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (farm_data_msg_payload_size_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the service CPU actual usage and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$container\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (container)(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request {{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows the service RAM actual consumption and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Service Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$container\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Kafka Client Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(consumer_group) (rate(kafka_consumer_rx_msgs_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "consumer: {{consumer_group}}"
    },
    {
     "expr": "sum by(producer_id) (-rate(kafka_producer_tx_msgs_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\", producer_id=~\"(head$)|(internal.*)\"}[1m]))",
     "legendFormat": "producer: {{producer_id}}"
    }
   ]
  },
  {
   "title": "Network IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(consumer_group) (rate(kafka_consumer_rx_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "consumer: {{consumer_group}}"
    },
    {
     "expr": "sum by(producer_id)(-rate(kafka_producer_tx_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\",producer_id=~\"(head$)|(internal.*)\"}[1m]))",
     "legendFormat": "producer: {{producer_id}}"
    }
   ]
  },
  {
   "title": "IO Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by(consumer_group) (rate(kafka_consumer_rx_msgs_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "consumer: {{consumer_group}}"
    },
    {
     "expr": "sum by(producer_id) (-rate(kafka_producer_tx_msgs_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "producer: {{producer_id}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_consumer_group_lag{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages in Producer Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Msg" } },
   "targets": [
    {
     "expr": "sum by (container)(kafka_producer_queue_msgs_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Current | {{container}}"
    },
    {
     "expr": "max by (container)(kafka_producer_queue_msgs_max_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Max | {{container}}"
    }
   ]
  },
  {
   "title": "Producer Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(kafka_producer_queue_msgs_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Current | {{container}}"
    },
    {
     "expr": "max by (container)(kafka_producer_queue_msgs_max_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Max | {{container}}"
    }
   ]
  },
  { "title": "MongoDB Client Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Distribution of Find Command Duration",
   "type": "bargauge",
   "description": "This shows how many find commands where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (mongodb_find_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Find Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(mongodb_find_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))/sum by (container)(rate(mongodb_find_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Upsert Command Duration",
   "type": "bargauge",
   "description": "This shows how many update with insertion commands where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (mongodb_upsert_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Upsert Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(mongodb_upsert_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))/sum by (container)(rate(mongodb_upsert_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Update Command Duration",
   "type": "bargauge",
   "description": "This shows how many update commands where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (mongodb_update_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Update Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(mongodb_update_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))/sum by (container)(rate(mongodb_update_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Delete Command Duration",
   "type": "bargauge",
   "description": "This shows how many delete commands where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (mongodb_delete_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Delete Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(mongodb_delete_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))/sum by (container)(rate(mongodb_delete_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Aggregate Command Duration",
   "type": "bargauge",
   "description": "This shows how many aggregation pipelines where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (mongodb_aggregate_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Aggregate Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(mongodb_aggregate_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))/sum by (container)(rate(mongodb_aggregate_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB IOps",
   "type": "timeseries",
   "description": "This shows how many aggregation pipelines where executed in the given time span and how much they took to execute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(sum (rate(mongodb_aggregate_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) or vector(0)) +\n(sum (rate(mongodb_find_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) or vector(0)) +\n(sum (rate(mongodb_upsert_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) or vector(0)) +\n(sum (rate(mongodb_update_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) or vector(0)) +\n(sum (rate(mongodb_delete_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m])) or vector(0))",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}