{
 "title": "Kafka To Mongo Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_info,k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\", namespace=\"$namespace\"},exported_container)"
    }
   },
   {
    "name": "consumer_group",
    "query": {
     "query": "label_values(kafka_consumer_rx_msgs_bytes_total{container=\"$container\"},consumer_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Msg Flushing Rate",
   "type": "timeseries",
   "description": "How many messages are effectively written to the persistence layer",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by(result)(rate(ka_flushed_messages_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "{{result}}: rate"
    }
   ]
  },
  {
   "title": "Current Aggregation Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container)(rate(ka_flushed_messages_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the service CPU actual usage and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$container\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows the service RAM actual consumption and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Service Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$container\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_msgs_bytes_total{container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_msgs_bytes_total{container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "Network IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_bytes_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_bytes_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "IO Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_msgs_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_msgs_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_consumer_group_lag{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "MongoDB Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Distribution of Update Command Duration",
   "type": "histogram",
   "description": "Buckers are in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(container, le)(mongodb_update_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of Delete Command Duration",
   "type": "histogram",
   "description": "Buckers are in milliseconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum by(container, le)(mongodb_delete_cmd_duration_milliseconds_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Update Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(container)(mongodb_update_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}/mongodb_update_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Delete Command Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(container)(mongodb_delete_cmd_duration_milliseconds_sum{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"}/mongodb_delete_cmd_duration_milliseconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}