{
 "title": "Mongezium Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_tx_bytes_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_rx_msgs_bytes_total{instance=~'$instance'}[1m])",
     "legendFormat": "{{instance}} Read"
    },
    {
     "expr": "-rate(kafka_producer_tx_msgs_bytes_total{instance=~'$instance'}[1m])",
     "legendFormat": "{{instance}} Write"
    }
   ]
  },
  {
   "title": "Network IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_rx_bytes_total{instance=~'$instance'}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "-rate(kafka_producer_tx_bytes_total{instance=~'$instance'}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "IO Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(kafka_consumer_rx_msgs_total{instance=~'$instance'}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "-rate(kafka_producer_tx_msgs_total{instance=~'$instance'}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Producer Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Messages in Producer Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Msg" } },
   "targets": [
    {
     "expr": "kafka_producer_queue_msgs_count{instance=~\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kafka_producer_queue_msgs_max_count{instance=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Producer Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_queue_msgs_size{instance=~\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "kafka_producer_queue_msgs_max_size{instance=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Producer Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kafka_producer_broker_throttle_avg{instance=~\"$instance\"}",
     "legendFormat": "Avg"
    },
    {
     "expr": "kafka_producer_broker_throttle_max{instance=~\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}