{
 "title": "Stream Processor Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_info,k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{k8sCluster=\"$cluster\", namespace=\"$namespace\"},exported_container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (container)(irate(sp_processed_messages_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"}[1m]))",
     "legendFormat": "{{container}} - rate"
    }
   ]
  },
  {
   "title": "Current Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(sp_processed_messages_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(sp_processed_messages_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", result=\"err\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows the service RAM actual consumption and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$container\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Service Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"$container\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the service CPU actual usage and the deploy request/limit",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$container\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", exported_container=~\"$container\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_msgs_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_msgs_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "Network IO Bytes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_bytes_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "IO Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (container)(rate(kafka_consumer_rx_msgs_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Read | {{container}}"
    },
    {
     "expr": "sum by (container)(-rate(kafka_producer_tx_msgs_total{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[$__rate_interval]))",
     "legendFormat": "Write | {{container}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_consumer_group_lag{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Fetch Queue Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_consumer_fetch_queue_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Messages in Producer Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "Msg" } },
   "targets": [
    {
     "expr": "sum by (container)(kafka_producer_queue_msgs_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Current | {{container}}"
    },
    {
     "expr": "max by (container)(kafka_producer_queue_msgs_max_count{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Max | {{container}}"
    }
   ]
  },
  {
   "title": "Producer Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(kafka_producer_queue_msgs_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Current | {{container}}"
    },
    {
     "expr": "max by (container)(kafka_producer_queue_msgs_max_size{k8sCluster=\"$cluster\", namespace=\"$namespace\",container=~\"$container\"})",
     "legendFormat": "Max | {{container}}"
    }
   ]
  }
 ]
}