apiVersion: v1
kind: Service
metadata:
  name: documentation-site
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: documentation-site
