{
 "title": "Fast Data - Bucket Storage Support",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "ingestionStorer",
    "query": {
     "query": "label_values(bss_bucket_upload_requests_total{k8sCluster=\"$cluster\",namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "ingestionReloader",
    "query": {
     "query": "label_values(fd_hd_bucket_download_request_total{k8sCluster=\"$cluster\",namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Ingestion Storer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion Storer IO Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_bytes_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Consumed Bytes - {{service}}"
    },
    {
     "expr": "-sum by(service)(kafka_producer_outgoing_byte_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Produced Bytes - {{service}}"
    }
   ]
  },
  {
   "title": "Ingestion Storer IO Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Consumed Messages - {{service}}"
    },
    {
     "expr": "-sum by(service)(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Produced Messages - {{service}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px\">\n<h1 style=\"margin: 0.2em 0;\">\n<a href=\"https://docs.confluent.io/platform/current/kafka/monitoring.html#consumer-metrics\" target=\"_blank\">\n    Consumer Metrics\n  </a>\n</h1>\n</div>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Consumer Lag Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(service, topic)(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Total Consumer Lag [msg]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Consumption Rate [msg/s]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Messages Production Rate [msg/s]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Consumed in the Time Range",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_consumed_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$ingestionStorer\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionStorer\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionStorer\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionStorer\", image!=\"\"})\n",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionStorer\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionStorer\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Fetch Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Fetch Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Fetch Latency"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Fetch Latency"
    }
   ]
  },
  {
   "title": "Available Service Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Commit Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_commit_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Commit Latency"
    }
   ]
  },
  {
   "title": "Rebalance Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_rebalance_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Rebalance Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_rebalance_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Rebalance Latency"
    }
   ]
  },
  {
   "title": "Consumer Join Time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_join_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Join Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_join_time_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Join Time"
    }
   ]
  },
  {
   "title": "Sync Time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Sync Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Sync Time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px;\">\n<h1 style=\"margin: 0.2em 0;\">\n  <a href=\"https://docs.confluent.io/platform/current/kafka/monitoring.html#producer-metrics\" target=\"_blank\">\n    Producer Metrics\n  </a>\n</h1>\n</div>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request/Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_request_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kafka_producer_response_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Response Rate"
    }
   ]
  },
  {
   "title": "Request Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_request_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Request Latency Across Replicas"
    },
    {
     "expr": "max(kafka_producer_request_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Request Latency Across Replicas"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_batch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_producer_batch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Average Compression Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_compression_rate_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Average IO Wait Time [ns]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_io_wait_time_ns_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionStorer\"})",
     "legendFormat": "Avg Wait Time Across Replicas"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
   "options": {
    "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px;\">\n<h1 style=\"margin: 0.2em 0;\">\n  Bucket Metrics\n</h1>\n</div>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ingestion Storer Bucket Upload Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service)(rate(bss_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionStorer\"}[4m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Storer Bucket Upload Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (service)(bss_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Storer Messages Written To Bucket",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (service)(bss_bucket_messages_written_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Storer Bucket Upload Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(bss_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionStorer\", status=\"OK\"}) / sum(bss_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionStorer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingestion Reloader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Ingestion Reloader IO Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_outgoing_byte_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Produced Bytes"
    }
   ]
  },
  {
   "title": "Ingestion Reloader IO Messages",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "sum(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Messages Produced"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 85 },
   "options": {
    "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px coral; border-radius: 3px; margin: 0 2px;\">\n<h1 style=\"margin: 0.2em 0;\">\n  <a href=\"https://docs.confluent.io/platform/current/kafka/monitoring.html#producer-metrics\" target=\"_blank\">\n    Producer Metrics\n  </a>\n</h1>\n</div>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_request_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Avg Request Latency Across Replicas"
    },
    {
     "expr": "max(kafka_producer_request_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Max Request Latency Across Replicas"
    }
   ]
  },
  {
   "title": "Average Request/Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_request_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kafka_producer_response_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Response Rate"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_batch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_producer_batch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$ingestionReloader\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionReloader\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionReloader\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionReloader\", image!=\"\"})",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionReloader\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$ingestionReloader\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "Average Compression Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_compression_rate_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Average IO Wait Time [ns]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_io_wait_time_ns_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$ingestionReloader\"})",
     "legendFormat": "Avg Wait Time Across Replicas"
    }
   ]
  },
  {
   "title": "Available Service Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\"$ingestionReloader\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 107 },
   "options": {
    "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px;\">\n<h1 style=\"margin: 0.2em 0;\">\n  Bucket Metrics\n</h1>\n</div>"
   },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ingestion Reloader Bucket Download Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service)(rate(fd_hd_bucket_download_request_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionReloader\"}[4m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Reloader Bucket Download Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 109 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by (service)(fd_hd_bucket_download_request_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionReloader\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingestion Reloader Bucket Download Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(fd_hd_bucket_download_request_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionReloader\", status=\"OK\"}) / sum(fd_hd_bucket_download_request_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"$ingestionReloader\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Organization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Organizer By Key IO Bytes Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_bytes_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Consumed Bytes"
      },
      {
       "expr": "-sum(kafka_producer_outgoing_byte_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Produced Bytes"
      }
     ]
    },
    {
     "title": "Data Organizer By Key IO Messages Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Consumed Messages"
      },
      {
       "expr": "-sum(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Produced Messages"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 130 },
     "options": {
      "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px\">\n<h1 style=\"margin: 0.2em 0;\">\n<a href=\"https://docs.confluent.io/platform/current/kafka/monitoring.html#consumer-metrics\" target=\"_blank\">\n    Consumer Metrics\n  </a>\n</h1>\n</div>"
     },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Consumer Lag Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "sum by(topic)(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Total Consumer Lag [msg]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Messages Consumption Rate [msg/s]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Messages Production Rate [msg/s]",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Messages Consumed in the Time Range",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum(kafka_consumer_fetch_manager_records_consumed_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 137 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", k8sCluster=\"$cluster\"}) by (container)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", resource=\"cpu\"}\n)",
       "legendFormat": "CPU Request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", resource=\"cpu\"}\n)",
       "legendFormat": "CPU Limit"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", image!=\"\"})",
       "legendFormat": "RAM Usage"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", resource=\"memory\"}\n)",
       "legendFormat": "RAM Request"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"data-organizer-by-key.*\", resource=\"memory\"}\n)",
       "legendFormat": "RAM Limit"
      }
     ]
    },
    {
     "title": "Fetch Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_fetch_manager_fetch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Average Fetch Size"
      },
      {
       "expr": "max(kafka_consumer_fetch_manager_fetch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Fetch Size"
      }
     ]
    },
    {
     "title": "Fetch Latency [ms]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Avg Fetch Latency"
      },
      {
       "expr": "max(kafka_consumer_fetch_manager_fetch_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Fetch Latency"
      }
     ]
    },
    {
     "title": "Available Service Replicas",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 151 },
     "targets": [
      {
       "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\"data-organizer-by-key.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Latency [ms]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Avg Commit Latency"
      },
      {
       "expr": "max(kafka_consumer_coordinator_commit_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Commit Latency"
      }
     ]
    },
    {
     "title": "Rebalance Latency [ms]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_coordinator_rebalance_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Avg Rebalance Latency"
      },
      {
       "expr": "max(kafka_consumer_coordinator_rebalance_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Rebalance Latency"
      }
     ]
    },
    {
     "title": "Consumer Join Time [ms]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_coordinator_join_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Avg Join Time"
      },
      {
       "expr": "max(kafka_consumer_coordinator_join_time_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Join Time"
      }
     ]
    },
    {
     "title": "Sync Time [ms]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Avg Sync Time"
      },
      {
       "expr": "max(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"data-organizer-by-key.*\"})",
       "legendFormat": "Max Sync Time"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 167 },
     "options": {
      "content": "<div style=\"text-align: center; vertical-align: middle; border: solid 1px #28B7E0; border-radius: 3px; margin: 0 2px;\">\n<h1 style=\"margin: 0.2em 0;\">\n  Bucket Metrics\n</h1>\n</div>"
     },
     "targets": [
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Data Organizer Bucket Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (service, fromRefinement)(rate(fd_hd_bucket_download_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer-by-key.*\"}[4m]))",
       "legendFormat": "Download - Organizer: {{fromRefinement}}"
      },
      {
       "expr": "sum by (service, fromRefinement)(rate(fd_hd_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer-by-key.*\"}[4m]))",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "Data Organizer Bucket Requests Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (service)(fd_hd_bucket_download_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer.*\"})",
       "legendFormat": "Download"
      },
      {
       "expr": "sum by (service)(fd_hd_bucket_upload_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer.*\"})",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "Data Organizer Cached Messages Loaded Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 169 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by (service)(fd_hd_cached_messages_loaded_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer.*\"})",
       "legendFormat": "Download"
      }
     ]
    },
    {
     "title": "Data Organizer Bucket Requests Success Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(fd_hd_bucket_download_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer.*\", status=\"OK\"}) / sum(fd_hd_bucket_download_requests_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", service=~\"data-organizer.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}