{
 "title": "Debezium CDC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Batch Processing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(service)(debezium_metrics_AverageBatchProcessingThroughput{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "max by(service)(debezium_metrics_MaxBatchProcessingThroughput{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Lag From Source",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod)(debezium_metrics_LagFromSourceInMilliseconds{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg by(service)(debezium_metrics_CommitThroughput{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Tables Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(service)(debezium_metrics_TotalTableCount{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of Events Seen",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service)(debezium_metrics_TotalNumberOfEventsSeen{k8sCluster=\"$cluster\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Number of Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(service)(rate(debezium_metrics_TotalNumberOfCreateEventsSeen{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "CREATE"
    },
    {
     "expr": "sum by(service)(rate(debezium_metrics_TotalNumberOfUpdateEventsSeen{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "sum by(service)(rate(debezium_metrics_TotalNumberOfDeleteEventsSeen{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"debezium-.*\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "CPU Usage - {{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"debezium-.*\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"debezium-.*\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"debezium-.*\", image!=\"\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"debezium-.*\", resource=\"memory\"}\n)",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"debezium-.*\", resource=\"memory\"}\n)",
     "legendFormat": "Memory Limit"
    }
   ]
  }
 ]
}