{
 "title": "Fast Data ingestion services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "service_selector",
    "query": ".*rtu.*|.*realtime.*|.*projection-storer.*"
   }
  ]
 },
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IO Bytes Throughput [Projection Storer only]",
   "type": "timeseries",
   "description": "How many bytes are read from and written to the ingestion channel (e.g. Kafka) per seconds",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_bytes_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "{{service}} - Input"
    },
    {
     "expr": "-sum by(service)(kafka_producer_outgoing_byte_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "{{service}} - Output"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Shows the service CPU actual usage and the deploy request/limit",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$service_selector\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$service_selector\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$service_selector\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Shows the service RAM actual consumption and the deploy request/limit",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$service_selector\", image!=\"\"}) by (container)",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$service_selector\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$service_selector\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "IO Messages Throughput [Projection Storer only]",
   "type": "timeseries",
   "description": "How many ingestion events are read from and written to the ingestion channel (e.g. Kafka) per seconds - This value is computed directly on the service",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "{{service}} - Input"
    },
    {
     "expr": "-sum by(service)(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "{{service}} - Output"
    }
   ]
  },
  {
   "title": "Available Service Replicas",
   "type": "timeseries",
   "description": "Shows the number of service service replicas deployed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\"$service_selector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Consumption Rate",
   "type": "timeseries",
   "description": "How many ingestion events are read from and written to the ingestion channel (e.g. Kafka) per seconds - This uses a message counter onto which is applied the rate function to obtain the throughput",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(service)(rate(kafka_consumer_fetch_manager_records_consumed_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[2m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Consumer Lag Per Topic",
   "type": "timeseries",
   "description": "Display for each ingestion topic the number of messages that have still to be consumed by the service",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(service, topic)(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "{{service}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Size",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_fetch_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Fetch Latency [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_fetch_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Fetch Latency"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Fetch Latency"
    }
   ]
  },
  {
   "title": "Consumer Join Time [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_group_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_join_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Join Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_join_time_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Join Time"
    }
   ]
  },
  {
   "title": "Sync Time [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_group_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Sync Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Sync Time"
    }
   ]
  },
  {
   "title": "Commit Latency [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_group_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Commit Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_commit_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Commit Latency"
    }
   ]
  },
  {
   "title": "Rebalance Latency [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#consumer_group_monitoring",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_rebalance_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Rebalance Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_rebalance_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Rebalance Latency"
    }
   ]
  },
  { "title": "Producer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Request Latency [ms]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#producer_sender_monitoring",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_request_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Request Latency Across Replicas"
    },
    {
     "expr": "max(kafka_producer_request_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Request Latency Across Replicas"
    }
   ]
  },
  {
   "title": "Average Request/Response Rate",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#producer_sender_monitoring",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_request_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kafka_producer_response_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Response Rate"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#producer_sender_monitoring",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_batch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_producer_batch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Average Compression Rate",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#producer_sender_monitoring",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_compression_rate_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Average IO Wait Time [ns]",
   "type": "timeseries",
   "description": "https://kafka.apache.org/documentation/#producer_sender_monitoring",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_io_wait_time_ns_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
     "legendFormat": "Avg Wait Time Across Replicas"
    }
   ]
  },
  {
   "title": "Execution Statistics [Projection Storer only]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batch Processing Time [s]",
     "type": "bargauge",
     "description": "Distribution of the time employed to process all the topic-partitions received within within a batch of ingestion messages. Note: commit phase not included",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by(le)(ps_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Processing Time Statistics",
     "type": "stat",
     "description": "Percentiles of the time to process all the topic-partitions received within within a batch of ingestion messages. Note: commit phase not included",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.01, sum by (service, le)(rate(ps_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.01"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (service, le)(rate(ps_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (service, le)(rate(ps_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (service, le)(rate(ps_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Projection Records Preparation Processing Time [s]",
     "type": "bargauge",
     "description": "Distribution of the time employed to take the raw ingestion messages and transform into projection events (cast + project operations)",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 86 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by(le)(ps_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Projection Records Preparation Time Statistics",
     "type": "stat",
     "description": "Percentiles of the time employed to take the raw ingestion messages and transform into projection events (cast + project operations)",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.01, sum by (service, le)(rate(ps_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.01"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (service, le)(rate(ps_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (service, le)(rate(ps_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (service, le)(rate(ps_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Batch Partition Processing Time [s]",
     "type": "bargauge",
     "description": "Distribution of the time employed to process a single topic-partition within a batch of ingestion messages",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by(le)(ps_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Partition Processing Time Statistics",
     "type": "stat",
     "description": "Percentiles of the time to process a single topic-partition within a batch of ingestion messages",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.01, sum by (service, le)(rate(ps_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.01"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (service, le)(rate(ps_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (service, le)(rate(ps_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (service, le)(rate(ps_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Storage Processing Time [s]",
     "type": "bargauge",
     "description": "Distribution of the time employed to store projection records onto the configured storage system",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by(le)(ps_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Storage Processing Time Statistics",
     "type": "stat",
     "description": "Percentiles of the time employed to store projection records onto the configured storage system",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.01, sum by (service, le)(rate(ps_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.01"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (service, le)(rate(ps_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (service, le)(rate(ps_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (service, le)(rate(ps_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.99"
      }
     ]
    },
    {
     "title": "Producer Processing Time [s]",
     "type": "bargauge",
     "description": "Distribution of the time employed to send the pr-update events onto the outgoing channel",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum by(le)(ps_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Producer Processing Time Statistics",
     "type": "stat",
     "description": "Percentiles of the time to send the pr-update events onto the outgoing channel",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.01, sum by (service, le)(rate(ps_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.01"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (service, le)(rate(ps_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.5"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (service, le)(rate(ps_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (service, le)(rate(ps_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__range])))",
       "legendFormat": "0.99"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongo Driver Commands Execution Time By Collection",
     "type": "timeseries",
     "description": "Average rate time employed by the MongoDB driver to create/update/delete projection records on the database",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(collection)(rate(mongodb_driver_commands_seconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parsed Messages",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(status)(rate(ps_parse_message_total{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$service_selector\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}