{
 "title": "Kafka Messages Dashboard",
 "tags": [ "kafka" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "consumer_group",
    "query": {
     "query": "label_values(kafka_consumergroup_lag{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}, consumergroup)"
    }
   },
   {
    "name": "consumergroup_subscribed_topics",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instant Total Messages Behind",
   "type": "stat",
   "description": "Show  the total amount of messages that needs to be read by selected Kafka consumer group (last measurement)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(kafka_consumergroup_lag{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\", namespace=\"$namespace\"}, 0))"
    }
   ]
  },
  {
   "title": "Instant consumption rate [msg/s]",
   "type": "stat",
   "description": "Shows the number of messages per second read by selected Kafka consumer group (last measurement)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deriv(kafka_consumergroup_current_offset{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Published messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{k8sCluster=~\"$cluster\", topic=~\"$consumergroup_subscribed_topics\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Consumed messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Total Messages Behind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\", namespace=\"$namespace\"}) by (consumergroup)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "timeseries",
   "description": "Shows the number of messages per second read by selected Kafka consumer group",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(deriv(kafka_consumergroup_current_offset{k8sCluster=\"$cluster\", consumergroup=~\"$consumer_group\", namespace=\"$namespace\"}[$__interval])) by (consumergroup))",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Message on 24h - by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{k8sCluster=~\"$cluster\", topic=~\"$consumergroup_subscribed_topics\"}[24h])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Consumers Deployed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\".*-realtime-updater$\"})\n# considering a specific consumer group, count the number of topics partitions (1 consumer-group for 1 partition) which offset has changed in the last interval",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Instant Consumer Lag",
   "type": "bargauge",
   "description": "Show for each topic of selected Kafka consumer group the amount of messages that needs to be read (last measurement)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(clamp_min(kafka_consumergroup_lag{consumergroup=~\"$consumer_group\", namespace=\"$namespace\"}, 0)) by (consumergroup, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Published messages per topic",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{k8sCluster=\"$cluster\", topic=~\"$consumergroup_subscribed_topics\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}