{
 "title": "Fast Data - Real-Time Updater",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "rtu",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IO Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_bytes_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Input"
    },
    {
     "expr": "-sum by(service)(kafka_producer_outgoing_byte_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", container=~\"$rtu\", k8sCluster=\"$cluster\"}) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$rtu\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$rtu\", resource=\"cpu\"}\n)",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$rtu\", image!=\"\"})",
     "legendFormat": "RAM Usage"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$rtu\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Request"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container=~\"$rtu\", resource=\"memory\"}\n)",
     "legendFormat": "RAM Limit"
    }
   ]
  },
  {
   "title": "IO Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(service)(kafka_consumer_fetch_manager_records_consumed_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Input"
    },
    {
     "expr": "-sum by(service)(kafka_producer_record_send_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Available Service Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by(deployment)(kube_deployment_status_replicas_available{k8sCluster=\"$cluster\", namespace=~\"$namespace\", deployment=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consumer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Consumer Lag Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(service, topic)(kafka_consumer_fetch_manager_records_lag{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Fetch Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_manager_fetch_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Fetch Latency"
    },
    {
     "expr": "max(kafka_consumer_fetch_manager_fetch_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Fetch Latency"
    }
   ]
  },
  {
   "title": "Consumer Join Time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_join_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Join Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_join_time_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Join Time"
    }
   ]
  },
  {
   "title": "Sync Time [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Sync Time"
    },
    {
     "expr": "max(kafka_consumer_coordinator_sync_time_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Sync Time"
    }
   ]
  },
  {
   "title": "Commit Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Commit Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_commit_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Commit Latency"
    }
   ]
  },
  {
   "title": "Rebalance Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_rebalance_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Rebalance Latency"
    },
    {
     "expr": "max(kafka_consumer_coordinator_rebalance_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Rebalance Latency"
    }
   ]
  },
  { "title": "Producer Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Request Latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_request_latency_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Request Latency Across Replicas"
    },
    {
     "expr": "max(kafka_producer_request_latency_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Request Latency Across Replicas"
    }
   ]
  },
  {
   "title": "Average Request/Response Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_request_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kafka_producer_response_rate{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Response Rate"
    }
   ]
  },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_batch_size_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Average Fetch Size"
    },
    {
     "expr": "max(kafka_producer_batch_size_max{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Max Fetch Size"
    }
   ]
  },
  {
   "title": "Average Compression Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_compression_rate_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Request Rate"
    }
   ]
  },
  {
   "title": "Average IO Wait Time [ns]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(kafka_producer_io_wait_time_ns_avg{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "Avg Wait Time Across Replicas"
    }
   ]
  },
  { "title": "Execution Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Batch Processing Time [s]",
   "type": "bargauge",
   "description": "Commit phase not included",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(le)(rtu_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Processing Time Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (service, le)(rate(rtu_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (service, le)(rate(rtu_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le)(rate(rtu_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le)(rate(rtu_consumer_batch_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Projection Records Preparation Processing Time [s]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(le)(rtu_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projection Records Preparation Time Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (service, le)(rate(rtu_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (service, le)(rate(rtu_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le)(rate(rtu_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le)(rate(rtu_processor_records_preparation_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Batch Partition Processing Time [s]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(le)(rtu_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Partition Processing Time Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (service, le)(rate(rtu_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (service, le)(rate(rtu_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le)(rate(rtu_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le)(rate(rtu_consumer_partition_processing_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Storage Processing Time [s]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(le)(rtu_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Processing Time Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (service, le)(rate(rtu_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (service, le)(rate(rtu_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le)(rate(rtu_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le)(rate(rtu_processor_storage_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Producer Processing Time [s]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum by(le)(rtu_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Processing Time Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum by (service, le)(rate(rtu_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m])))",
     "legendFormat": "0.01"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (service, le)(rate(rtu_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (service, le)(rate(rtu_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (service, le)(rate(rtu_processor_producer_bucket{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"new-rtu.*\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Mongo Driver Commands Execution Time By Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(collection)(rate(mongodb_driver_commands_seconds_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Topic-Partitions per Consumer Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "avg by(service)(rate(rtu_consumer_topic_partition_per_batch_count_count{k8sCluster=\"$cluster\",namespace=\"$namespace\",service=~\"$rtu\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}