{
 "title": "Fast Data - Single Views",
 "tags": [ "fast-data" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, k8sCluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{k8sCluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "portfolioOrigin",
    "query": {
     "query": "label_values(svc_pcs_handled_total{k8sCluster=\"$cluster\",namespace=\"$namespace\"}, portfolioOrigin)"
    }
   },
   {
    "name": "svType",
    "query": {
     "query": "label_values(svc_pcs_handled_total{k8sCluster=\"$cluster\",namespace=\"$namespace\"}, svType)"
    }
   },
   {
    "name": "svcDeployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{k8sCluster=\"$cluster\", namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "fastDataServices",
    "query": ".+realtime-updater.+,single-view-trigger.+,single-view-creator.+"
   },
   {
    "name": "resolutionMethod",
    "query": {
     "query": "label_values(svc_pcs_handled_total{k8sCluster=\"$cluster\",namespace=\"$namespace\"}, resolutionMethod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Single View General stats  [$resolutionMethod]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "resolutionMethod"
  },
  {
   "title": "Current Processing Rate [SV/s]",
   "type": "stat",
   "description": "Current number of projection changes that are processed per second to generate Single Views (in the current time-frame)",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(svc_pcs_handled_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Avg Processing Rate [SV/s]",
   "type": "stat",
   "description": "Average number of projection changes that are processed per second to generate Single Views (in the current time-frame)",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(svc_pcs_handled_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Max Processing Rate [SV/s]",
   "type": "stat",
   "description": "Maximum number of projection changes that are processed per second to generate Single Views (in the current time-frame)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(svc_pcs_handled_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total # SV processed",
   "type": "stat",
   "description": "Total amount of Projection Changes processed current time-frame to generate Single Views (approximated)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(svc_pcs_handled_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\"})"
    }
   ]
  },
  {
   "title": "Total # SV Generation Errors",
   "type": "stat",
   "description": "Total amount of Projection Changes processed current time-frame to generate Single Views (approximated)",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\", errorType!=\"ERROR_SEND_SVC_EVENT\"})"
    }
   ]
  },
  {
   "title": "Total # Kafka Production Errors",
   "type": "stat",
   "description": "Total amount of Projection Changes processed current time-frame to generate Single Views (approximated)",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\", errorType=\"ERROR_SEND_SVC_EVENT\"})"
    }
   ]
  },
  { "title": "Strategy Execution Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Strategy execution time (count)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(svtg_strategy_execution_time_bucket{le=\"0.1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 0.1ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_bucket{le=\"1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"0.1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "0.1 - 1 ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_bucket{le=\"5\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_bucket{le=\"10\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"5\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "5 - 10ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_bucket{le=\"50\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"10\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "10 - 50 ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_bucket{le=\"100\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"50\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "round(sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) - sum(increase(strategy_execution_time_bucket{le=\"100\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "> 100ms"
    }
   ]
  },
  {
   "title": "Strategy execution time (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(svtg_strategy_execution_time_bucket{le=\"0.1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svtg_strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 0.1ms"
    },
    {
     "expr": "(sum(increase(strategy_execution_time_bucket{le=\"1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"0.1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "0.1 - 1 ms"
    },
    {
     "expr": "(sum(increase(strategy_execution_time_bucket{le=\"10\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"1\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "1 - 10 ms"
    },
    {
     "expr": "(sum(increase(strategy_execution_time_bucket{le=\"100\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"10\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "10 - 100 ms"
    },
    {
     "expr": "(sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(strategy_execution_time_bucket{le=\"100\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "> 100ms"
    }
   ]
  },
  {
   "title": "Strategy execution miliseconds in SVTG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(svtg_strategy_execution_time_bucket{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval])) / sum by(pod) (rate(svtg_strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Strategy execution miliseconds in SVTG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(projectionName) (rate(svtg_strategy_execution_time_sum{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval])) / sum by(projectionName) (rate(svtg_strategy_execution_time_count{k8sCluster=\"$cluster\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Single Views Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "SVC Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(svc_pcs_handled_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", resolutionMethod=~\"$resolutionMethod\"}[$__interval])) by (portfolioOrigin, svType, resolutionMethod)",
     "legendFormat": "{{portfolioOrigin}} - {{svType}} - {{resolutionMethod}}"
    }
   ]
  },
  {
   "title": "SVC Validation Error",
   "type": "timeseries",
   "description": "Shows the amount of validation errors obtained in the last 2 minutes from generating SV.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"VALIDATION_ERROR\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC No Generation Error",
   "type": "timeseries",
   "description": "Shows the amount of SV not generated in the last 2 minutes due to missing data or other related reasons.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"NO_SV_GENERATED\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC single PC to multiple SV Error",
   "type": "timeseries",
   "description": "Shows the amount of error in the last 2 minutes due to a violation of the 1-to-1 relationship between a PC and the generated SV.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"MORE_SVS_GENERATED_FROM_ONE_PROJECTION_CHANGE\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC Max Aggregation Time Error",
   "type": "timeseries",
   "description": "Shows the amount of max aggregation time error (exceeded allowed computation time) obtained in the last 2 minutes from generating SV.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"SINGLE_VIEW_AGGREGATION_MAX_TIME\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC Unknown Error",
   "type": "timeseries",
   "description": "Shows the amount of unknown errors obtained in the last 2 minutes from generating SV.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"UNKNOWN_ERROR\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC Kafka Send Error",
   "type": "timeseries",
   "description": "Shows the amount of errors obtained in the last 2 minutes while producing messages to Kafka.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(svc_error_gen_total{k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\", errorType=\"ERROR_SEND_SVC_EVENT\"}[$__interval])) by (portfolioOrigin)",
     "legendFormat": "{{portfolioOrigin}}"
    }
   ]
  },
  {
   "title": "SVC Operation Types",
   "type": "timeseries",
   "description": "Shows which kind of operation are performed generating Single Views",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(increase(svc_operation_type_total{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__interval])) by (operationType)",
     "legendFormat": "{{operationType}}"
    }
   ]
  },
  {
   "title": "Projection To Single View Time (count)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 150ms"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 2s"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 5s"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 15s"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 30s"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 1m"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 2m"
    },
    {
     "expr": "round(sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "> 2m"
    }
   ]
  },
  {
   "title": "Projection To Single View Time (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 150ms"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 2s"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 5s"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 15s"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 30s"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) /  sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 1m"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 2m"
    },
    {
     "expr": "(sum(increase(svc_projection_to_single_view_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_projection_to_single_view_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_projection_to_single_view_time_bucket{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "> 2m"
    }
   ]
  },
  {
   "title": "PC To Single View Time (count)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 150ms"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 2s"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 5s"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 15s"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 30s"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 1m"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "< 2m"
    },
    {
     "expr": "round(sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "> 2m"
    }
   ]
  },
  {
   "title": "PC To Single View Time (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 150ms"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 2s"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 5s"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 15s"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"15000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 30s"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"30000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))  / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 1m"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"60000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "< 2m"
    },
    {
     "expr": "(sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_pc_total_handle_time_bucket{le=\"120000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_pc_total_handle_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "> 2m"
    }
   ]
  },
  {
   "title": "SV Creation Time (count)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(svc_creation_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "creation time below 150ms"
    },
    {
     "expr": "round(sum(increase(svc_creation_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "creation time between 150ms and 2s"
    },
    {
     "expr": "round(sum(increase(svc_creation_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "creation time between 2s and 5s"
    },
    {
     "expr": "round(sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])))",
     "legendFormat": "creation time above 5s"
    }
   ]
  },
  {
   "title": "SV Creation Time (%)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(svc_creation_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "creation time below 150ms"
    },
    {
     "expr": "(sum(increase(svc_creation_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"150\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "creation time between 150ms and 2s"
    },
    {
     "expr": "(sum(increase(svc_creation_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=~\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"2000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "creation time between 2s and 5s"
    },
    {
     "expr": "(sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range])) - sum(increase(svc_creation_time_bucket{le=\"5000\", k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))) / sum(increase(svc_creation_time_count{k8sCluster=\"$cluster\", namespace=\"$namespace\", portfolioOrigin=~\"$portfolioOrigin\", svType=~\"$svType\"}[$__range]))",
     "legendFormat": "creation time above 5s"
    }
   ]
  },
  { "title": "Fast Data Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "RTU CPU Usage",
   "type": "timeseries",
   "description": "Shows how many CPUs (from K8s nodes) Real-Time Updaters services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{k8sCluster=\"$cluster\", namespace=\"$namespace\", pod=~\".+realtime-updater.+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVTG CPU Usage",
   "type": "timeseries",
   "description": "Shows how many CPUs (from K8s nodes) Single View Triegger Generator services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{k8sCluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*single-view-trigger-generator.+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVC CPU Usage",
   "type": "timeseries",
   "description": "Shows how many CPUs (from K8s nodes) Single View Creator services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{k8sCluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*single-view-creator.+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTU Memory Usage",
   "type": "timeseries",
   "description": "Shows how much memory (from K8s nodes) Real-Time Updaters services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\".+realtime-updater.+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVTG Memory Usage in MB",
   "type": "timeseries",
   "description": "Shows how much memory (from K8s nodes) Single View Trigger Generator services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\".*single-view-trigger-generator.+\"}) by (pod) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVC Memory Usage",
   "type": "timeseries",
   "description": "Shows how much memory (from K8s nodes) Single View Creator services are currently consuming.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", k8sCluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\", pod=~\".*single-view-creator.+\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTU Replicas",
   "type": "timeseries",
   "description": "Shows how many pods of Real-Time Updater services are currently deployed in the namespace.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\".*realtime-updater.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVTG Replicas",
   "type": "timeseries",
   "description": "Shows how many pods of Single View Trigger Generator services are currently deployed in the namespace.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 112 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\".*single-view-trigger-generator.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SVC Replicas",
   "type": "timeseries",
   "description": "Shows how many pods of Single View Creator services are currently deployed in the namespace.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{k8sCluster=\"$cluster\", namespace=\"$namespace\", deployment=~\".*single-view-creator.*\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}