flowchart TD
    NewDeviceData[New device data] --> |Save raw data| RawDataSaved[Raw data saved]
    NewDeviceData --> |Error saving data| Failure[Failure]
    RawDataSaved --> |Creating job| JobCreated[Job created]
    RawDataSaved --> |Sending response| Success[Success]
    JobCreated --> |Starting job| JobStarted[Job started]
    JobCreated --> |Error starting job| JobFailed[Job failed]
    JobStarted --> |Normalizing data| NormalizedData[Data normalized]
    JobStarted --> |Error normalizing data| JobFailed
    NormalizedData --> |Submit detections| DetectionsSubmitted[Detections submitted]
    NormalizedData --> |Error submitting detections| DetectionsNotSubmitted[Detections failed]
    DetectionsSubmitted --> Success
    DetectionsNotSubmitted --> JobFailed