name: "Generate Embeddings"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  generate-embeddings:
    runs-on: ubuntu-latest
    env:
      DOCUMENTATION_VERSION: ${{ github.event_name == 'push' && github.ref_name || '' }}
    steps:
      - uses: eic/trigger-gitlab-ci@v3
        with:
          url: https://git.tools.mia-platform.eu
          project_id: ${{ vars.MIA_ASSISTANT_GITLAB_PROJECT_ID }}
          token: ${{ secrets.MIA_ASSISTANT_GITLAB_TOKEN }}
          variables: |
            GENERATE_EMBEDDINGS=true
            DOCUMENTATION_VERSION=${{ env.DOCUMENTATION_VERSION }}
          ref_name: master
