name: "Generate Embeddings"

on:
  workflow_dispatch:

jobs:
  generate-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: eic/trigger-gitlab-ci@v3
        with:
          url: https://git.tools.mia-platform.eu
          project_id: ${{ vars.MIA_ASSISTANT_GITLAB_PROJECT_ID }}
          token: ${{ secrets.MIA_ASSISTANT_GITLAB_TOKEN }}
          variables: |
            GENERATE_EMBEDDINGS=true
          ref_name: master
