name: "Generate Embeddings"

on:
  workflow_dispatch:
    inputs:
      console_version:
        description: "Console version"
        required: true
        default: "latest"
      embedding_model:
        description: "Embedding model used to generate the embeddings"
        required: true
        default: "text-embedding-3-small"

jobs:
  generate-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: eic/trigger-gitlab-ci@v3
        with:
          url: https://git.tools.mia-platform.eu
          project_id: ${{ vars.MIA_ASSISTANT_GITLAB_PROJECT_ID }}
          token: ${{ secrets.MIA_ASSISTANT_GITLAB_TOKEN }}
          variables: |
            GENERATE_EMBEDDINGS=true
            CONSOLE_VERSION=${{ github.event.inputs.console_version }}
            EMBEDDING_MODEL=${{ github.event.inputs.embedding_model }}
          ref_name: master